### ISSUE TITLE
NodeScriptTask args eating the command

### ISSUE THREAD

**Issue by vibdev** [PeredurOmega/GradleNodePlugin#6]
I would like to pass arg to one of my npm scripts:
```
tasks.named<NodeScriptTask>("dev") {
	args.set("arg1")
}
```
However it seems like like the args are killing the command
`Executing: <pathToNode>/npm run arg1`

instead of 

`Executing: <pathToNode>/npm run dev arg1`

------

I think switching to an arg list similar to `DependenciesInstallTask.kt` will fix it

**Comment by PeredurOmega** [comment]
Fixed in 2.0.3
